[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "Edit with Neovim" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "application/json", use = "edit" },
	{ mime = "application/xml", use = "edit" },
	{ mime = "application/x-wine-extension-ini", use = "edit" },
]
