# ~/.config/starship.toml

add_newline = true

# Line 1: Info. Line 2: Prompt
format = """
$username\
$directory\
$git_branch\
$python\
$nodejs\
$nix_shell\
$line_break\
$character"""

right_format = ""

[directory]
style = "bold blue"
format = "[$path]($style) "
truncation_length = 4

[git_branch]
symbol = " "
style = "purple"
format = "on [$symbol$branch]($style) "

[python]
symbol = "py"
style = "yellow"
format = "via [${symbol}${version}]($style) "

[nodejs]
symbol = "js"
style = "green"
format = "via [${symbol}${version}]($style) "

[nix_shell]
symbol = "nix"
format = "via [$symbol]($style) "

[username]
# Shows "root" in red if sudo/root, otherwise hidden
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false

[character]
# Simple arrow for input
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
